name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  WORKING_DIR: .

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: pnpm install

      - name: Build
        working-directory: ${{ env.WORKING_DIR }}
        run: pnpm run build -- --mode gh-pages
        env:
          NODE_ENV: production

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
